[package]
name = "study_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47", features = ["full"] }
axum = { version = "0.7", features = ["ws"] }
futures = "0.3"
bytes = "1.0"